baseURL: 'https://blog.cklau.cc'
title: "特倫蘇的日與夜"
theme: ["hugo-notice", "ladder"]
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: "CKLAU's WEBSITE"
homepage: 'https://blog.cklau.cc'
defaultContentLanguage: 'en'
paginate: 10
googleAnalytics: G-PXB7GSCQBT
menu:
  main:
    - name: Project
      url: /projects
      weight: 1
    #- name: Tags
    #  url: /tags
    #  weight: 2
    - name: Friends
      url: /friends
      weight: 3
    #- name: Gadgets
    #  url: /gadgets
    #  weight: 4

params:
  brand: CKLAU's WEBSITE
  avatarURL: /images/avatar.jpeg
  author: Junjie(Terence) Liu
  authorDescription: Statistics Student
  info: All sciences are, in the abstract, mathematics; All judgements are, in their rationale, statistics.
  favicon: /images/icon.png
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode #icy-dark-mode
  comments:
    giscus:
      enable: false
      repo: TerenceLiu98/terenceliu98.github.io
      repo_id: R_kgDOIELpKQ
      category: General
      category_id: DIC_kwDOIELpKc4CT1A1
      mapping: pathname
      position: top
      lang: en
      loading: lazy
    utteranc:
      enable: true
      repo: TerenceLiu98/terenceliu98.github.io
      issueTerm: url
      theme: github-light
  analytics:
    google:
      SiteVerificationTag: GTM-MC97JQPW
  #  umami:
  #    enable: true
  #    website_id: 2320eaa6-a90b-471c-b6ca-e79dadde8c4c
  #    url: https://umami-ochre-nu.vercel.app/hugo-ladder.js
  social:
    - name: RSS
      pre: >- 
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 11a9 9 0 0 1 9 9"></path><path d="M4 4a16 16 0 0 1 16 16"></path><circle cx="5" cy="19" r="1"></circle></svg>
      url: "https://terenceliu98.github.io/index.xml"
    - name: GitHub
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>
      url: 'https://github.com/TerenceLiu98'
    - name: Twitter
      pre: >-
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>
      url: 'https://twitter.com/TerenceLau_ST'
languages:
  en:
    languageName: EN
  zh:
    languageName: 中
    brand: 特倫蘇的日與夜
    author: 劉駿傑
    authorDescription: 非 「非典型」 统计系学生
    info: 在抽象的意义下，一切科学都是数学；在理性的世界里，所有的判断都是统计
    menu:
      main:
        - name: 文章
          url: /post
          weight: 1
        - name: 分类
          url: /tags
          weight: 2
        - name: 项目
          url: /projects
          weight: 3
        - name: 朋辈
          url: /friends
          weight: 4
taxonomies:
  series: series
  tag: tags