baseURL: 'https://blog.cklau.cc'
languageCode: 'en'
title: "特倫蘇的日與夜"
theme: ["hugo-simplecite", "cklau-hugo-theme"]
description: "特倫蘇 (Junjie Liu / CKLAU) 的個人網站——統計、機器學習研究筆記、論文與生活記錄。"
homepage: 'https://blog.cklau.cc'
enableRobotsTXT: true
enableGitInfo: true
markup:
  goldmark:
    renderer:
      unsafe: true

minify:
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false
    css:
      precision: 2

menu:
  main:
    - name: "[Blog]"
      url: /post
      weight: 1
    - name: "[Scientia]"
      url: /scientia
      weight: 2
    - name: "[Projects]"
      url: /projects
      weight: 3
    - name: "[Links]"
      url: /links
      weight: 4

params:
  brand: CKLAU's WEBSITE
  avatarURL: https://avatars-githubusercontent.webp.se/TerenceLiu98
  description: "特倫蘇 (Junjie Liu / CKLAU) 的個人網站——統計、機器學習研究筆記、論文與生活記錄。"
  author: Junjie LIU
  images:
    - https://avatars-githubusercontent.webp.se/TerenceLiu98
  beian: 粤ICP备2022102668号
  authorDescription: Statistics Student
  info: All sciences are, in the abstract, mathematics; All judgements are, in their rationale, statistics. -- C. R. Rao
  favicon: /images/logo.svg
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode #icy-dark-mode
  comments:
    giscus:
      enable: false
      repo: TerenceLiu98/terenceliu98.github.io
      repo_id: R_kgDOIELpKQ
      category: General
      category_id: DIC_kwDOIELpKc4CT1A1
      mapping: pathname
      position: top
      lang: en
      loading: lazy
    utteranc:
      enable: true
      repo: TerenceLiu98/terenceliu98.github.io
      issueTerm: url
      theme: github-light