baseURL: 'https://blog.cklau.cc'
title: "特倫蘇的日與夜"
theme: ["hugo-simplecite", "cklau-hugo-theme"]
description: "CKLAU's WEBSITE"
homepage: 'https://blog.cklau.cc'
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: "[Blog]"
      url: /post
      weight: 1
    - name: "[Scientia]"
      url: /post/scientia
      weight: 2
    - name: "[Links]"
      url: /links
      weight: 3

params:
  brand: CKLAU's WEBSITE
  avatarURL: https://avatars-githubusercontent.webp.se/TerenceLiu98
  description: "CKLAU's WEBSITE"
  author: Junjie LIU
  beian: 粤ICP备2022102668号
  authorDescription: Statistics Student
  info: All sciences are, in the abstract, mathematics; All judgements are, in their rationale, statistics. -- C. R. Rao
  favicon: /images/logo.svg
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
  darkModeTheme: data-dark-mode #icy-dark-mode
  comments:
    giscus:
      enable: false
      repo: TerenceLiu98/terenceliu98.github.io
      repo_id: R_kgDOIELpKQ
      category: General
      category_id: DIC_kwDOIELpKc4CT1A1
      mapping: pathname
      position: top
      lang: en
      loading: lazy
    utteranc:
      enable: true
      repo: TerenceLiu98/terenceliu98.github.io
      issueTerm: url
      theme: github-light