baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Hello World'
theme = "paper"

disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

[params]
  # color style
  color = 'linen'                 # linen, wheat, gray, light

  # header social icons
  #twitter = 'YOUR_TWITTER_ID'     # twitter.com/YOUR_TWITTER_ID
  github = 'TerenceLiu98'       # github.com/YOUR_GITHUB_ID
  #instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
  rss = true                      # show rss icon with link

  # home page profile
  avatar = 'https://pic2.zhimg.com/v2-54d4d4d5b007d119e3bc16a1287e4189_xll.jpg'       # Gravatar email or image url(e.g. "https://deno.land/logo.svg")
  name = 'Terence Junjie LIU'
  #bio = 'YOUR_BIO'

  # misc
  disableHLJS = false              # disable requesting highlight.js
  monoDarkIcon = true             # show monochrome dark mode icon